//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K2Field.Utilities.Testing.WF.UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string K2Server {
            get {
                return ((string)(this["K2Server"]));
            }
            set {
                this["K2Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://workspace.denallix.com/ViewFlow/ViewFlow.aspx?ViewTypeName=ProcessView&K2S" +
            "erver=k2server.denallix.com:5252&HostServerName=k2server.denallix.com&HostServer" +
            "Port=5555&ProcessID=")]
        public string ViewFlowURL {
            get {
                return ((string)(this["ViewFlowURL"]));
            }
            set {
                this["ViewFlowURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\..\\SampleWorkflow\\NewStyleTestFiles\\All.xml")]
        public string TestFile {
            get {
                return ((string)(this["TestFile"]));
            }
            set {
                this["TestFile"] = value;
            }
        }
    }
}
